import "@radix-ui/themes/styles.css";
import './theme-config.css';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Theme, ThemePanel } from "@radix-ui/themes";
import Navbar from './Navbar';

const inter = Inter({
  subsets: ['latin'],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: 'Issue Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.variable} bg-black min-h-screen m-0`}>
        <Theme appearance="light" accentColor="violet">
          <Navbar />

          {/* Main Section with Black Background and Padding */}
          <main className="flex flex-col items-center justify-center p-6 md:p-12 space-y-10 text-white w-full min-h-screen bg-black">
            {/* Main Content */}
            <div className="max-w-7xl w-full px-4 sm:px-6 md:px-8 bg-black">
              {children}
            </div>
          </main>

          {/* Footer Section with Black Background and Padding */}
          <footer className="bg-black text-white py-6 text-center mt-0">
            <div className="bg-black p-6">
              <p className="text-sm">
                &copy; {new Date().getFullYear()} Issue Tracker App. All Rights Reserved.
              </p>
            </div>
          </footer>

          <ThemePanel />
        </Theme>
      </body>
    </html>
  );
}

