import "@radix-ui/themes/styles.css";
import './theme-config.css';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Theme, ThemePanel } from "@radix-ui/themes";
import Navbar from './Navbar';

const inter = Inter({
  subsets: ['latin'],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: 'Issue Tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full w-full">
      <body className={`${inter.variable} bg-black text-white m-0 p-0 h-full w-full`}>
        <Theme appearance="light" accentColor="violet">
          <Navbar />

          {/* Main Section */}
          <main className="flex-grow flex flex-col items-center justify-center w-full min-h-screen">
            {/* Main Content */}
            <div className="w-full">
              {children}
            </div>
          </main>

          {/* Footer Section */}
          <footer className="bg-black text-white py-6 text-center w-full">
            <div className="p-4">
              <p className="text-sm">
                &copy; {new Date().getFullYear()} Issue Tracker App. All Rights Reserved.
              </p>
            </div>
          </footer>

          <ThemePanel />
        </Theme>
      </body>
    </html>
  );
}

